---
# tasks file for hello_motd
- name: Generate greeting and store result
  ansible.builtin.set_fact:
    hello_motd_greeting: "Hello {{ hello_motd_friend_name }}"

- name: Store test in /etc/motd
  ansible.builtin.copy:
    content: "{{ hello_motd_greeting }}\n"
    dest: /etc/motd
    mode: "0644"
  become: true
...
